keys:
  - &homelab01 age1fqkz7r00szqmnj72uuycsvxmd2p3hkqr05nncuhjfzmc2x0fnytsjw8028
  - &laptop age13dq6y4q8vdr4sp7nqp5gmh2luvk05cpp02s6x88nw3cl8znc7slq6a2dq8

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *homelab01
          - *laptop
