# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  up:
    desc: Update all the flake inputs
    cmds:
      - nix flake update --commit-lock-file

  upp:
    desc: Update specific input
    cmds:
      - nix flake update {{.CLI_ARGS}} --commit-lock-file

  history:
    desc: List all generations of the system profile
    cmds:
      - nix profile history --profile /nix/var/nix/profiles/system

  repl:
    desc: Open a nix shell with the flake
    cmds:
      - nix repl -f flake:nixpkgs

  clean:
    desc: Remove all generations older than 7 days
    cmds:
      - sudo nix profile wipe-history --profile /nix/var/nix/profiles/system --older-than 7d
      - nix profile wipe-history --profile $"($env.XDG_STATE_HOME)/nix/profiles/home-manager" --older-than 7d

  gc:
    desc: Garbage collect all unused nix store entries
    cmds:
      - sudo nix-collect-garbage --delete-older-than 7d
      - nix-collect-garbage --delete-older-than 7d

  shell:
    desc: Enter a shell session which has all the necessary tools for this flake
    cmds:
      - nix shell nixpkgs#git nixpkgs#neovim nixpkgs#colmena

  gcroot:
    desc: Show all the auto gc roots in the nix store
    cmds:
      - ls -al /nix/var/nix/gcroots/auto/

  verify-store:
    desc: Verify all the store entries
    cmds:
      - nix store verify --all
